from __future__ import annotations

import json
from typing import TypeVar

from pydantic import BaseModel, ValidationError

from src.brain.json_tools import extract_json_schema
from src.llmclient.llm_client import LLMClientBase, Message, MessageContent, MessageRole
from src.llmclient.llm_config_registry import LLMTask
from src.utils.logger import configure_logger
from src.utils.sqllogger import SQLLogger

TModel = TypeVar("TModel", bound=BaseModel)

_log = configure_logger("structured_output")
_sql_logger = SQLLogger()

_REPAIR_SYSTEM_PROMPT = (
    "You are a JSON repair assistant. The JSON you receive was generated by a creative AI "
    "and contains valuable content, but has a syntax or structural error preventing it from being parsed. "
    "Your task: fix ONLY the error. Preserve ALL existing fields, values, and content exactly as they are. "
    "Do NOT simplify, strip, omit, or regenerate any content. "
    "If the JSON is truncated, close unclosed structures with the minimum characters needed. "
    "Output only the corrected JSON object — no explanation, no markdown fences, no extra text."
)


def _build_repair_messages(
    result_type: type[TModel],
    bad_response: str,
    error: Exception,
) -> list[Message]:
    schema_str = json.dumps(result_type.model_json_schema(), indent=2)
    user_text = (
        f"The following JSON failed to parse. Fix the syntax error while keeping ALL content intact.\n\n"
        f"Parse error:\n{error}\n\n"
        f"Minimum structural requirement (the fixed JSON must satisfy this, but must also preserve all original fields):\n{schema_str}\n\n"
        f"JSON to fix (preserve all content):\n{bad_response}"
    )
    return [
        Message(role=MessageRole.SYSTEM, content=MessageContent(text=_REPAIR_SYSTEM_PROMPT)),
        Message(role=MessageRole.USER, content=MessageContent(text=user_text)),
    ]


def parse_with_retry(
    messages: list[Message],
    result_type: type[TModel],
    llm_client: LLMClientBase,
    max_retries: int = 2,
    reasoning: bool = False,
    task: LLMTask = LLMTask.ARCHITECT,
) -> TModel:
    """
    Call the LLM and validate the response against a Pydantic model.
    On validation failure, retries with a focused repair prompt instead of
    re-sending the full original prompt, which can be very large.

    Use this for synchronous, blocking operations (oracle seeds, mission generation)
    where retry resilience matters more than logging individual attempts.
    For fire-and-forget background tasks that need parse-failure logging, use
    SummaryMemory._call_structured instead.
    """
    current_messages = list(messages)
    last_error: Exception | None = None
    response: str = ""
    last_failure_response: str = ""
    last_failure_error: Exception | None = None

    for attempt in range(max_retries + 1):
        try:
            response = llm_client.chat_completion(
                messages=current_messages,
                reasoning=reasoning if attempt == 0 else False,
                task=task,
            )
            json_str = extract_json_schema(response)
            result = result_type.model_validate_json(json_str)
            if attempt > 0:
                _log.info("ParseRepair succeeded | model=%s | attempt=%d", result_type.__name__, attempt)
                _sql_logger.log_parse_repair(
                    model_type=result_type.__name__,
                    attempt=attempt,
                    validation_error=str(last_failure_error),
                    bad_response=last_failure_response,
                    repair_output=response,
                    success=True,
                )
            return result
        except (ValidationError, ValueError) as exc:
            if attempt > 0:
                _log.warning("ParseRepair failed | model=%s | attempt=%d | error=%s", result_type.__name__, attempt, exc)
                _sql_logger.log_parse_repair(
                    model_type=result_type.__name__,
                    attempt=attempt,
                    validation_error=str(last_failure_error),
                    bad_response=last_failure_response,
                    repair_output=response,
                    success=False,
                )
            else:
                _log.warning("ParseWithRetry initial failure | model=%s | error=%s", result_type.__name__, exc)
            last_failure_response = response
            last_failure_error = exc
            last_error = exc
            if attempt < max_retries:
                # Replace the full original context with a minimal repair prompt.
                # The original system prompt can be very large (examples, instructions, etc.)
                # and re-sending it on every retry wastes tokens and time.
                current_messages = _build_repair_messages(result_type, response, exc)

    raise ValueError(
        f"Failed to parse LLM response after {max_retries + 1} attempt(s). "
        f"Last error: {last_error}"
    )
